# jf: url

validate:
  - type: npm-jest
    path: node-app-test
  - type: python-pytest
    path: .github/actions/parse-manifest

build:
  - type: pack-cli
    path: node-app-test
    # id: default
    # builder: pack builder
    # repository: docker-dev
    # tags vs tagsource    
  - id: api
    type: docker
    path: node-app-test
    registry: test-gar
    repository: docker-dev
    # context: node-app-test
    # application-name: my-app
    # dockerfile: /app/Dockerfile
    # tags vs tagsource 

deploy:
  #target = default
  - type: cloudrun
    region: us-central1
    gcp-project: sbx-test-501815
    identity-project: id-proj
  # target = api,
  - type: azure-ca
    environment: dev
    target: api
    region: eastus
    azure-subscription: nxg-text
    azure-rg: nxg-rg  
  # image = httpd (so no target)
  - type: cloudrun
    region: us-central1
    image: httpd
    gcp-project: sbx-test-501815
    identity-project: id-proj