# Caller Workflow for CICD pipeline of nxg-github-actions
name: Application CI/CD

on:
    push:
        branches:
            - main
            - deploys
            - dev-test
    pull_request:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    cicd:
        uses: nxtgenhub-com/nxg-github-actions/.github/workflows/_reusable-app-cicd.yml@deploys
        secrets: inherit